#include "InfraSource.h"




InfraSource::InfraSource()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-101--1794b3d:130fb012621:-8000:000000000000141E begin
{
}
// section -64--88-1-101--1794b3d:130fb012621:-8000:000000000000141E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

InfraSource::~InfraSource()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -56--125--124--47--295a459c:130ffa31ff0:-8000:0000000000001072 begin
{
}
// section -56--125--124--47--295a459c:130ffa31ff0:-8000:0000000000001072 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
