#include "iStatus.h"




void iStatus::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-101--1794b3d:130fb012621:-8000:00000000000013E8 begin
{
}
// section -64--88-1-101--1794b3d:130fb012621:-8000:00000000000013E8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

iStatus::iStatus()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-101--1794b3d:130fb012621:-8000:0000000000001407 begin
{
}
// section -64--88-1-101--1794b3d:130fb012621:-8000:0000000000001407 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
